# Generated by Django 3.2.10 on 2022-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0002_auto_20200703_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('translation:created', 'Translation created'), ('translation:deleted', 'Translation deleted'), ('translation:approved', 'Translation approved'), ('translation:unapproved', 'Translation unapproved'), ('translation:rejected', 'Translation rejected'), ('translation:unrejected', 'Translation unrejected'), ('comment:added', 'Comment added'), ('comment:deleted', 'Comment deleted'), ('comment:updated', 'Comment updated')], max_length=50),
        ),
    ]
